Dockerfile
there was 2 errors
1. bug to copy line without final slash
2. dist folder missing with follow error
`2018-12-05T11:28:20.123Z - info: cannot load manifest: Error: Cannot find module '../../../dist/manifest.json'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at _callee$ (/app/src/lib/middleware/manifest-middleware.js:7:18)
at tryCatch (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
at Generator.invoke [as _invoke] (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
at Generator.prototype.(anonymous function) [as next] (/app/node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js: …
=> the dockerfile build a failure image

src/client/stylesheets/custom.scss
Padding added: **0px 10px 0px 10px**
=> adding padding to TransactionDetailSection 10px left - 10px right

src/shared/blocks/blocks.js, src/shared/transfers/transfers.js, src/shared/votes/votes.js
=> issue 24, Add age to Block Transfers and Vote pages

src/lib/middleware/i18n-middleware.js, translations/it.yaml
=> issue-26, Italian translation file 

src/server/gateways/coin-market-cap.js, src/shared/common/nav/nav-handler.js, src/shared/common/nav/nav.js
=> navbar: added IOTX/BTC column

config/default.js, src/client/stylesheets/custom.scss, src/shared/app.js, src/shared/common/inputfields/text-input-field.js, src/shared/common/root/root-html.js, src/shared/wallet/new-wallet.js, src/shared/wallet/unlock-wallet.js, src/shared/wallet/wallet-app.js
#17 
Changelog:
- Fixed and upgrade to font-awesome (5.0.9)
- unlock-wallet page:
- added X to close warning panel
- private key field is a password input type
- private key field has an icon **eye-slash**
- new-wallet  page
- private key field has an icon **eye**
=> improve wallet UI

src/shared/common/nav/nav-handler.js, src/shared/common/nav/nav.js, src/shared/common/site-url.js, translations/en.yaml, translations/it.yaml
=> added fuzzy search

src/shared/wallet/contract/deploy.js
=> skip warnings while creating abi/json (smart contract)

src/shared/wallet/transfer/transfer-input.js, translations/en.yaml, translations/it.yaml
#43 
Do you like my solution? The Data (hex) field will be automatically update on by data text field (using onChange event)!
=> Added new field text (data) into trasfer input page

src/shared/blocks/blocks.js, src/shared/common/inputfields/text-input-field.js, src/shared/common/nav/nav.js, src/shared/executions/executions.js, src/shared/transfers/transfers.js, src/shared/votes/votes.js, src/shared/wallet/unlock-wallet.js
#62 
Fix key press on "unlock wallet" and "search bar"
=> Issue 62 - Manage enter key

src/client/stylesheets/mobile.scss, src/shared/app.js, src/shared/blocks/blocks.js, src/shared/executions/executions.js, src/shared/transfers/transfers.js, src/shared/votes/votes.js, src/shared/wallet/unlock-wallet.js
#61 
Fix Votes, Transfers, Blocks and Executions
=> Issue 61 - mobile layout

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts
=> porting function to resolve part 1

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts, src/shared/debug-resolver.tsx, src/shared/queries.ts
=> add resolver rpc call method

src/shared/common/image-utils.tsx, src/shared/common/styles/style-color.tsx, src/shared/home/bp-render.tsx, src/shared/home/bp-table.tsx, translations/en.yaml, translations/zh-cn.yaml
=>  update bptable render

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/scalars/map-scalar.ts, src/shared/debug-resolver.tsx
=> Port resolve p3

src/shared/common/top-bar.tsx, translations/en.yaml, translations/zh-cn.yaml
>
add "blockchain" to topbar with a dropdown
Fixes #
```release-note
```
=> add "blockchain" to topbar with a dropdown

babel.config.js, package.json, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, translations/en.yaml, translations/zh-cn.yaml
>
> 
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add publicKeyToAddress

src/shared/common/top-bar.tsx
>
add caret down icon
Fixes #
```release-note
```
=> patch issue 92

package.json
>
> /kind bug
> 
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add pre-push

package.json, webpack.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> cut bundle size

package.json, src/server/server-routes.tsx, src/shared/actions/actions.tsx, src/shared/address-details/action-table.tsx, src/shared/app.tsx, src/shared/block/block-detail.tsx, src/shared/common/from-now.ts, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #94 
```release-note
```
=> add /actions

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
**Which issue(s) this PR fixes**: 
Fixes #136 
```release-note
```
=> #136 topbar responsiveness and highlight

src/shared/address-details/address-details.tsx
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #133 
```release-note
```
=> #133 balance formatting: 4 digits precision

package.json, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts
>
> /kind bug
> /kind design
> /kind flake
/kind documentation
Fixes #138 
```release-note
```
=> add comments to antenna and update doc

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #146
```release-note
```
=> #146 topbar responsiveness

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #109 
```release-note
```
=> #109 add actions in block in /block/:block

src/shared/home/bp-table.tsx
>
> /kind bug
> /kind design
> /kind flake
related to #148
```release-note
```
=> #148 table responsiveness

src/shared/common/error-page.tsx
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #147 
```release-note
```
=> #147 fix: back home not working

src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts, src/shared/debug-resolver.tsx, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #69 
```release-note
```
=> add estimate gas for action query

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #158 
```release-note
```
=> #158 hide mobile menu on route change

package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #155 
```release-note
```
=> #155 finish up address-details pagination

src/api-gateway/resolvers/antenna-types.ts, src/shared/common/top-bar.tsx, src/shared/queries.ts, tslint.json
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #159 
```release-note
```
=> #159 improve search box

locale/zh_CN.yaml, src/api-gateway/resolvers/antenna-types.ts, src/shared/action/action-detail.tsx, src/shared/address-details/action-table.tsx, src/shared/block/block-detail.tsx, src/shared/common/get-action-type.ts, src/shared/debug-resolver.tsx, src/shared/queries.ts, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #166
```release-note
```
=> add more fields to action core

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #110 
```release-note
```
=> #110 fix types annotation by using ICtx in antenna resolver

src/shared/common/top-bar.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #179
```release-note
```
=> #179 fix placeholder of search box on topbar

src/shared/address-details/action-table.tsx, src/shared/block/block-detail.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #165
```release-note
```
=> #165 fix block detail pagination

src/client/stylesheets/main.scss, src/shared/action/action-detail.tsx, src/shared/actions/actions.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/block/blocks.tsx, translations/en.yaml, translations/zh-CN.yaml
Fixes # 202
```release-note
```
=> pretty page title && sections title - Issues 202

package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/meta.ts, src/shared/common/footer.tsx, src/shared/queries.ts, tsconfig.json
>
> /kind bug
> /kind design
> /kind flake
Fixes #173 
```release-note
```
=> #173 add version information to footer

src/client/stylesheets/main.scss, src/shared/common/copy-button-clipboard.tsx, translations/en.yaml, translations/zh-CN.yaml
Fixes # 193
```release-note
copy to clipboard btn improve
```
=> copy to clipboard btn improve

src/shared/action/action-detail.tsx, src/shared/address-details/action-table.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #192
```release-note
```
=> Add gas price in action

src/shared/action/action-detail.tsx, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/block/blocks.tsx, src/shared/common/from-now.ts, src/shared/home/home.tsx, translations/en.yaml, translations/zh-CN.yaml
Fixes #177 
```release-note
```
=> revisit all pages and fix translations

src/shared/common/footer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #215 
```release-note
```
=> #215 if loading or error, just do not display

src/shared/app.tsx, src/shared/common/scroll-top.tsx
Fixes #216 
```release-note
```
=> add ScrollToTop Component to app - issues 216

src/shared/wallet/unlock-wallet.tsx, src/shared/wallet/wallet.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #197 
```release-note
```
=> #197 unlock private key with iotex-antenna

src/shared/block/block-detail.tsx
> /kind bug
Fixes #224 
```release-note
```
=> transferAmount formRau

src/shared/actions/actions.tsx
> /kind bug
Fixes #223 
```release-note
```
=> change actions list count from 10 to 30

package.json, src/api-gateway/api-gateway.graphql, src/shared/action/action-receipt.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/home/bp-table.tsx, src/shared/home/home.tsx, tsconfig.json
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #
```release-note
```
=> fix type error

src/client/stylesheets/main.scss, src/shared/app.tsx, src/shared/common/form-item-layout.ts, src/shared/wallet/new-wallet.tsx, src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/unlock-wallet.tsx, src/shared/wallet/wallet.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #229 
```release-note
```
=>  #229 P2 1.0 Transfer Token

.storybook/contract-interaction-success.tsx, src/shared/common/contract-interaction-success.tsx, src/shared/common/paragraph.tsx, translations/en.yaml
Fixes #239 
```release-note
```
=> contract interaction success page

src/client/stylesheets/main.scss
Fixes #267 
```release-note
```
=> add hover boxshadow change

src/shared/action/action-detail.tsx, src/shared/queries.ts, translations/en.yaml
Fixes #270 
```release-note
```
=> action detail issues

src/shared/wallet/contract/cards.tsx
Fixes #278 
```release-note
```
=> fixed the box-shadow

src/shared/common/page-title.tsx, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/choose-function.tsx, src/shared/wallet/contract/contract-layout.tsx, src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/transfer/transfer.tsx
Fixes #279 
```release-note
```
=> add titles(icon, h2 title, html title)

package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/shared/common/apollo-ssr.tsx, src/shared/common/from-now.ts, src/shared/queries.ts
>
> 
/kind api-change
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> bump antenna

src/shared/common/copy-button-clipboard.tsx, src/shared/common/tooltip-button.tsx, src/shared/wallet/account-section.tsx
Fixes #290 
```release-note
```
=> Update wallet area

src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/unlock-wallet.tsx
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #283  #285 #282 
```release-note
```
=> fix various issue

src/shared/common/routes.ts, src/shared/wallet/wallet.tsx
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #289 
```release-note
```
=> #289 fix router push issues

src/client/stylesheets/main.scss, src/shared/wallet/transfer/transfer.tsx
Fixes #284 
```release-note
```
=> change modal-btn styles to default by antd

src/shared/common/site-url.ts, src/shared/wallet/contract/vote.tsx, src/shared/wallet/wallet.tsx, translations/en.yaml
Fixes #286 
```release-note
```
=> add contract vote page

src/shared/actions/actions.tsx, src/shared/address-details/action-table.tsx, src/shared/block/block-detail.tsx
> /kind bug
Fixes #299 
```release-note
```
=> init pagination total number

src/shared/wallet/contract/contract-layout.tsx, src/shared/wallet/transfer/transfer.tsx
> /kind bug
Fixes #287 
```release-note
```
=> fix input  border right show error

src/shared/common/confirm-contract-modal.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
/kind bug
Fixes #301 
```release-note
```
=> #301 fix wallet transfer

src/client/stylesheets/main.scss, src/shared/common/rules.ts, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #238 #237 
```release-note
```
=> #238 update contract interact ui

src/shared/common/routes.ts, src/shared/wallet/contract/contract-layout.tsx, src/shared/wallet/contract/vote.tsx, src/shared/wallet/wallet.tsx
Fixes #288 
```release-note
```
=> add back to smart contract

translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #316 
```release-note
```
=> #316 add translations

src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/choose-function.tsx, src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx
Fixes #307 
```release-note
```
=> import antd component not from root

src/shared/common/confirm-contract-modal.tsx, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/wallet.tsx
>
> /kind bug
> /kind design
> 
/kind feature
> /kind flake
Fixes #303 
```release-note
add contract deploy
```
=> add deploy contract

src/shared/wallet/contract/interact.tsx
=> fix console log error

src/shared/queries.ts, src/shared/wallet/contract/interact.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #371 
```release-note
```
=> #371 confirm contract interaction before sending out

src/shared/action/action-detail.tsx, src/shared/action/action-receipt.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #310 #380
```release-note
```
=> #310 #380 add unit

src/api-gateway/resolvers/antenna.ts, src/shared/actions/actions.tsx, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx
Fixes #338 
```release-note
```
=> change pagination order

src/shared/address-details/action-table.tsx
kind bug
Fixes #391 
```release-note
Need to double check which data should be downloaded by user
```
=> Fixed issue #391: replace data field with download icon

src/shared/action/action-detail.tsx, src/shared/action/action-receipt.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #380 #389 
```release-note
```
=> #389 #380 fix too many Rau & add Action Fee

package.json, src/shared/action/action-detail.tsx, src/shared/action/action-receipt.tsx, src/shared/actions/actions.tsx, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/block/blocks.tsx, src/shared/common/apollo-client.ts, src/shared/common/apollo-error-handling.ts, src/shared/home/home.tsx
bug
This PR is to handle the error of all graph queries.
Fixes #108 
This PR is using the `apollo-link-error` package to handle the error of all graph queries as a recommendation from https://www.apollographql.com/docs/react/features/error-handling.
NONE
```release-note
```
=> Fixed #108: error handling of all graphql queries

package.json, src/server/server-routes.tsx, src/shared/action/action-detail.tsx, src/shared/actions/actions.tsx, src/shared/app.tsx, src/shared/block/block-detail.tsx, src/shared/block/blocks.tsx, src/shared/common/navigation.tsx, src/shared/common/top-bar.tsx, src/shared/home/home.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #395 
```release-note
```
=> #395 add navigation

src/shared/block/block-detail.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> improve block detail page

src/shared/wallet/new-wallet.tsx
bug
Fixes #416 make private key input default hidden
This PR changes the private key to be hidden as default.
```release-note
```
=> Fixed #416: make private key input default hidden

src/shared/wallet/contract/deploy.tsx, translations/en.yaml
ui-change
This PR is to support user process multiple contracts to abi.
Fixes #298 
This PR contains ui-change as below:
**1. For multiple valid contracts**
**2. For a single valid contract**
**3. For none valid contract**
```release-note
Need to double check sign function before merge.
```
=> Fixed #298: Process multiple contract to abi

package.json, src/api-gateway/api-gateway.ts, src/shared/action/action-detail.tsx, src/shared/address-details/action-table.tsx, src/shared/app.tsx, src/shared/block/block-detail.tsx, src/shared/common/navigation.tsx, src/shared/common/styles/style-padding.tsx
This reverts commit d050d04d1af2622834a2c644d691dbd905ca476c.
>
> /kind bug
> /kind design
> /kind flake
/kind cleanup
Fixes #412  #410 
```release-note
```
=> [new wireframe] split action list from block detail 

src/shared/app.tsx, src/shared/block/block-detail.tsx, src/shared/block/blocks.tsx
>
> /kind bug
> /kind design
> /kind flake
route-change
Fixes #422 
```release-note
```
=> replace /block/:hash to /block/:height

src/shared/action/action-receipt.tsx
bug
Fixes #427 
```release-note
```
=> #427 fix action fee unit

src/shared/wallet/broadcast-status.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #476 
```release-note
```
=> add copy button in transfer

src/server/server-routes.tsx, src/shared/action/action-detail.tsx, src/shared/common/apollo-error-handling.ts, src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #441 
```release-note
```
=> remove graphl error when address not found

translations/en.yaml
update translation
Fixes #474 
```release-note
```
=> #474 update translation

src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts, src/shared/debug-resolver.tsx, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
/kind feature
Fixes #495 
```release-note
```
=>  add getEpochMeta to antenna resolver #495

src/shared/common/footer.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> make ui look good in mobile

src/shared/common/top-bar.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Add wallet entry to tools that in topbar.
Fixes #541
```release-note
```
=> feature: add wallet entry to tools, close #541

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/api-gateway/resolvers/antenna.ts
…se #540 .
>
> /kind bug
> /kind design
> /kind flake
Add getServerMeta and readState api for antenna rpc methods.
Fixes #540
```release-note
```
=> api: add getServerMeta and readState api for antenna rpc methods, close #540

src/shared/common/footer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #518 
```release-note
```
=> add social link

src/client/stylesheets/main.scss, src/shared/common/styles/style-color.tsx, src/shared/common/top-bar.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> change menu item hover color and adjust size

package.json, src/shared/common/top-bar.tsx, src/shared/home/home.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/iotexproject/iotex-react-components/issues/110
```release-note
```
=> update bptable 2.1.0

src/shared/common/show-qrcode-button.tsx, src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #564 
```release-note
```
=> fix issue 564

src/shared/block/block-detail.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
Leave more space between contents and footer
```
=> Leave more space between contents and footer

src/shared/common/top-bar.tsx
=> Fixed #561: remove go back home on top bar

src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/choose-function.tsx
=> Fixed #559: remove description texts of contract selection

src/shared/action/action-detail.tsx, src/shared/actions/actions.tsx, src/shared/address-details/action-table.tsx
Don't use server render for action query.
feature
Fixes #581 
None
=> Fixed #581: update getActions query settings

src/shared/wallet/contract/vote.tsx
>
> /kind bug
> /kind design
> /kind flake
Correct title label for vote for delegate, #574 
Fixes #
```release-note
```
=> [wallet] correct title label for vote for delegate

src/client/stylesheets/main.scss, src/shared/home/block-list.tsx, src/shared/home/home.tsx
feature
Fixes #560 
This PR added interval poll for each 10s to list latest block
- **Added Show More link to block page**
- **Added Animation**
=> Fixed #560: listen on new blocks every 10 sec

src/shared/common/rules.ts, src/shared/wallet/contract/deploy.tsx
> /kind bug
#593 
1. remove amount field from contract deploy ui
2. change amount component to optional
3. fix deploy contract abi type bug
=> fix deploy contract ui bug

src/shared/wallet/contract/interact.tsx
>
> /kind bug
> /kind design
> /kind flake
Use input instead of textarea for contract Address field
Fixes #597 
```release-note
```
=> Use input instead of textarea

package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts
> /kind flake
update iotex-antenna to version 0.15.3
=> update antenna to 0.15.3

src/shared/common/styles/style-color.tsx, src/shared/home/block-list.tsx, src/shared/home/home.tsx
=> Fixed block list issues

src/shared/common/rules.ts, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/deploy.tsx, translations/en.yaml
bug
Fixes #595 
Ref. @ququzone:  "this is because contract has non-empty parameters constructor, so we should add dynamic parameter input field by abi."
=> Fixed #595: smart contract deploy error

src/erc20/erc20.ts, src/shared/wallet/transfer/erc20-transfer.tsx
bug
This PR is to fix the balance display issue for ERC20 tokens.
=> Fix ERC20 balance issue

src/shared/block/block-detail.tsx
>
> /kind bug
> /kind design
> /kind flake
Email sharing on hash in action page is not correct
Fixes #594 
```release-note
```
=> change the content of subject and body by email sharing action

src/shared/wallet/contract/interact.tsx, translations/en.yaml
/kind feature
Fixes #610 
```release-note
```
=> add copy bytecode button

src/client/javascripts/memory-main.tsx, src/electron/src/main.js, src/electron/src/renderer.js, src/shared/app.tsx, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/wallet-reducer.ts, src/shared/wallet/wallet.tsx
>
> /kind bug
> /kind design
> 
/kind feature
> /kind flake
#466
```release-note
```
=> add query params to contract interact

src/shared/common/icons/iotex.svg.tsx, src/shared/home/home.tsx
=> Adding IOTex Explorer icon at home page

src/erc20/erc20Token.ts, src/shared/wallet/account-section.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
feature
This PR is for adding error handling while process support for ERC20 Tokens. 
Fixes #
```release-note
```
=> [Wallet] Adding errors handling for ERC20 Tokens support

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fix react unique key error
Fixes #645 
```release-note
```
=> TopBarComponent report unique key error

src/shared/common/top-bar.tsx, translations/en.yaml
=> Fixed #648: "WALLET" => "Wallet"

src/erc20/abi.ts
update standard ERC20 abi to VITA abi.
=> update erc20 abi to support vita

config/default.js, src/erc20/erc20Token.ts, src/server/server-routes.tsx, src/shared/common/apollo-ssr.tsx, src/shared/wallet/account-section.tsx, src/shared/wallet/chain-network-switch.tsx, src/shared/wallet/wallet-actions.ts, src/shared/wallet/wallet-reducer.ts
feature
Ref. https://github.com/iotexproject/iotex-explorer/pull/641#issuecomment-498851166
Fixes #
NONE
=> Add preset ERC20 Tokens 

src/shared/action/action-detail.tsx
> /kind bug
fix ERC20 transfer decode for action detail page.
=> fix erc20 decode error

src/shared/common/apollo-client.ts, src/shared/home/home.tsx, src/shared/wallet/broadcast-status.tsx, src/shared/wallet/chain-network-switch.tsx
bug
Fixes #664 
NONE
```release-note
```
=> Fixed #664: switching network provider should change the graphql endpoint as well

src/shared/common/rules.ts, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/transfer/transfer.tsx
=> Set amount as optional and set default to 0 for interact with contract

src/shared/common/xconf.ts, src/shared/wallet/contract/interact.tsx
ui-change
Fixes #670 #671 #672 
```release-note
```
=> Improve UI/UX for interact with contract

package.json
Reverts iotexproject/iotex-explorer#620
=> Revert "Update dependency typescript to v3.5.1"

src/shared/wallet/wallet-tabs.tsx
ui-change
Fixes #674 
```release-note
```
=> Fixed #674: move votes to the third tab

src/shared/common/rules.ts, src/shared/wallet/contract/cards.tsx, translations/en.yaml
=> Fixed #707: ABI shouldn't be required for contract deployment

src/shared/wallet/transfer/transfer.tsx
=> Fixed #676: Button label is wrong

src/shared/common/rules.ts, src/shared/wallet/account-section.tsx, src/shared/wallet/generate-authorized-message-form-modal.tsx, translations/en.yaml
=> Fixed #725: Prepare message for user to sign in #723

config/default.js, src/shared/wallet/chain-network-switch.tsx
Fixed init state for account section
update
This PR is to add VITA production to preset tokens. It also fixes a minor issue that account session does fetch the preset tokens at the beginning.
Fixes #
=> Adding VITA production

src/erc20/vita.ts
>
/kind bug
> /kind design
> /kind flake
Fix Signature encoding problem
Fixes #
```release-note
Tested in testnet, with this new encoding, everything works as expected
```
=> fix encoding problem of signature

config/default.js, src/erc20/abi.ts, src/erc20/erc20.ts, src/erc20/token.ts, src/server/server-routes.tsx, src/shared/action/action-detail.tsx, src/shared/wallet/account-section.tsx, src/shared/wallet/bid-form-modal.tsx, translations/en.yaml
=> Fixed #748: add bid to vita operations

package.json, src/electron/src/config.js, src/electron/src/main.js, src/electron/src/renderer.js, src/electron/src/server.js, src/electron/src/service.js, src/erc20/vita.ts
>
> /kind bug
> /kind design
/kind feature
> /kind flake
Wallet side of wss. Create a wss server, and waiting for connection.
Fixes #
```release-note
```
=> Wss service

src/shared/wallet/generate-authorized-message-form-modal.tsx
/kind bug
Disabled the generate button onclick and if the nonce changes it will become active.
=> Disabled generate button until nonce changes

src/erc20/token.ts
Fix https://github.com/iotexproject/iotex-explorer/issues/752
=> Reduce the gas limit from 1M to 100K

src/erc20/token.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> bump CLAIM_GAS_LIMIT to 200K

src/shared/wallet/contract/cards.tsx, src/shared/wallet/unlock-by-keystore-file.tsx
=> Fixed #743: Disable password weakness checking

src/client/stylesheets/main.scss, src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #769 
```release-note
```
=>  add search box in topbar

src/shared/wallet/contract/interact.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #751 
```release-note
```
=>  read contract trigger popup

package.json, src/electron/src/config.js, src/electron/src/main.js, src/electron/src/renderer.js, src/electron/src/server.js, src/electron/src/service.js, src/erc20/vita.ts
>
/kind bug
> /kind design
> /kind flake
Electron cannot restart normally.
Fixes #
```release-note
```
=> Fix wss service bug

src/erc20/erc20.ts, src/erc20/token.ts, src/erc20/vita.ts, src/shared/wallet/account-section.tsx, src/shared/wallet/bid-form-modal.tsx, translations/en.yaml
feature
This PR is to estimate gas and verify account balance before execution method ( claim, claimAs, bid). If there is an insufficient balance then notify the user for the error.
Fixes #740 
=> Estimate gas before execution

src/erc20/token.ts, src/shared/common/setup-big-number.ts
bug
Fixes #782 
```release-note
```
=> Fixed #782: Limit decimal places to 2

src/shared/action/action-detail.tsx
feature
Fixes #783 
```release-note
```
=> Fixed #783: Adding timestamp to action detail

src/erc20/erc20.ts, src/erc20/token.ts, src/shared/wallet/bid-form-modal.tsx
bug
This PR is to fix bid action failed all the time. The root cause of the issue is about wrong input order for the gasPrice and gasLimit at the executionMethod call.
Fixes #
```release-note
```
=> Fix bid action failed all the time

src/erc20/erc20.ts, src/shared/wallet/account-section.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
bug
Fixes #796 #797 
```release-note
```
=> Fixed #796 #797 which are relate to estimateGas issue

src/shared/wallet/download-keystore-form.tsx, src/shared/wallet/wallet-tabs.tsx, translations/en.yaml
feature
Fixes #772 
```release-note
```
=> Fixed #772: Add option to export keystore for existing accounts 

src/shared/action/action-detail.tsx
=> Removed unit 'Rau' from gas limit on action page (#806)

src/shared/common/footer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix footer policy bug

package.json, src/api-gateway/api-gateway.graphql, src/client/javascripts/main.tsx, src/client/javascripts/memory-main.tsx, src/electron/package.json, src/electron/src/main.js, src/electron/src/renderer.js, src/electron/src/server.js, src/electron/src/service.js, src/erc20/vita.ts, src/shared/common/routes.ts, src/shared/wallet/contract/cards.tsx, src/shared/wallet/sign-and-send-envelop-modal.tsx, src/shared/wallet/sign.tsx, src/shared/wallet/wallet-reducer.ts, src/shared/wallet/wallet-tabs.tsx
>
> /kind bug
> /kind design
> 
/kind feature
> /kind flake
Fixes #
```release-note
```
=> Dummy sign channel

src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/transfer/transfer.tsx
=> update gas price

config/default.js
bug
Fixes #798 
```release-note
```
=> Fixed #798: outdated test network vita contract address

src/erc20/token.ts, src/shared/wallet/generate-authorized-message-form-modal.tsx
bug
Fixes #803 
```release-note
```
=> Fixed #803: two digits nonce of claimAs cannot succeed

src/shared/wallet/account-section.tsx
bug
Fixes #827 
```release-note
```
=> Fixed #827: [wallet] need toast that message 'Insufficient balance for gas' 

translations/de.yaml, translations/it.yaml, translations/zh-CN.yaml
=> Suggested action to human readable

src/shared/home/home.tsx, src/shared/home/search-box.tsx
/kind backend-change
Fixes #811
=> Search without click icon

src/shared/common/action-not-found.tsx
=> fixed broken page title(#836)

src/shared/wallet/account-section.tsx
=> Show unclaimed vita amount 

src/client/stylesheets/main.scss
>
> /kind bug
> /kind design
> /kind flake
style preview:
Fixes #847 
```release-note
```
=> remove card shadow

src/server/server-routes.tsx
=> allowed unknown routes to land on not found page(#861)

src/shared/app.tsx
bug
This PR is to fix minor syntax issue of pr #851 
Fixes #
```release-note
```
=> Correct css syntax issue

package.json
=> update antenna to 0.19.0

src/electron/package.json, src/shared/home/search-box.tsx
>
> /kind bug
> 
/kind cleanup
> /kind design
> /kind flake
Related to #720
```release-note
```
=> bump electron-builder

src/server/server-routes.tsx
>
> 
/kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix api gateway

translations/en.yaml
=> added text total balance - action fee

src/shared/home/stats-area.tsx, src/shared/home/stats/actions-card.tsx, src/shared/home/stats/map-card.tsx, translations/en.yaml
Remove not available tabs of the Map
ui-change
Fixes #882 
=> Fixed 882: update the stats area

package.json
the upgrade of css-animation from 1.5.0 to 1.6.0 break the deploy, fix the version
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> control css-animation version to be 1.5.0

src/shared/wallet/contract/cards.tsx
bug
Fixes #917 
```release-note
```
=> Fixed #917: cursor pointer for smart contract buttons

src/electron/package.json, src/electron/src/index.html, src/electron/src/main.js, src/electron/src/server.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #921 
```release-note
```
=> add wallet wss

src/shared/home/stats/actions-card.tsx, src/shared/home/stats/candidates-card.tsx, src/shared/home/stats/productivity-card.tsx, src/shared/home/stats/stats-card.tsx, src/shared/home/stats/tps-card.tsx, src/shared/home/stats/votes-card.tsx
=> Number spin to stats

src/electron/package.json
>
> /kind bug
> 
/kind cleanup
> /kind design
> /kind flake
Fixes #
```release-note
```
=> bump iotex-wallet

src/shared/home/charts/area-chart.tsx, src/shared/home/charts/circle-chart.tsx
=> Fixed #924: console error

src/erc20/erc20.ts, src/shared/address-details/action-table.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/common/sign-in-modal.tsx, src/shared/home/block-list.tsx, src/shared/home/home.tsx, src/shared/home/search-box.tsx, src/shared/home/stats-area.tsx, src/shared/home/stats/map-card.tsx, src/shared/home/stats/stats-card.tsx, src/shared/wallet/account-section.tsx, src/shared/wallet/add-custom-rpc-form-modal.tsx, src/shared/wallet/add-custom-tokens-form-modal.tsx, src/shared/wallet/authorized-message-form-modal.tsx, src/shared/wallet/bid-form-modal.tsx, src/shared/wallet/chain-network-switch.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/generate-authorized-message-form-modal.tsx, src/shared/wallet/lock-alert.tsx, src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/wallet-tabs.tsx
cleanup
Fixes #923 
This PR requires to optimize from iotex-react components as well.
TODO: 
NONE
=> Fixed #923: optimize bundle size

src/shared/home/stats/productivity-card.tsx, translations/de.yaml, translations/en.yaml, translations/it.yaml, translations/zh-CN.yaml
=> changed chart title

src/shared/wallet/account-section.tsx
=> removed primary color from claim dropdown

src/client/javascripts/memory-main.tsx, src/electron/package.json, src/electron/src/renderer.js, src/electron/src/service.js, src/shared/wallet/get-antenna.ts
>
> /kind bug
> /kind design
> 
/kind feature
> /kind flake
Fixes #
```release-note
```
=> add GET_ACCOUNTS to ws plugin

src/shared/wallet/bid-form-modal.tsx
=> refresh balance after bid complete

src/shared/action/action-detail.tsx, src/shared/common/action-not-found.tsx, src/shared/common/error-page.tsx, translations/en.yaml
=> fixed pending tx page title

src/client/stylesheets/main.scss
=> added responsiveness to address page(#926)

src/electron/src/main.js, src/electron/src/service.js
feature
Fixes #940 
```release-note
```
=> Fixed #940: [wallet] pop up to the top of the screen if there is a tx to sign

src/shared/common/button.tsx, src/shared/common/top-bar.tsx, src/shared/common/write-contract-modal.tsx, src/shared/wallet/account-section.tsx, src/shared/wallet/broadcast-status.tsx, src/shared/wallet/contract/contract-layout.tsx, src/shared/wallet/lock-alert.tsx
bug
Fixes #939 
```release-note
```
=> Fixed #939: [wallet] cursor pointer for go back link

src/shared/wallet/contract/cards.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
=> moved gas limit above the send button

src/shared/common/top-bar.tsx
=> added german to language dropdown

src/shared/wallet/contract/interact.tsx
bug
**Which issue(s) this PR fixes**: 
Fixes #948 
```release-note
```
=> Fixed #948: [Wallet] readContract display error

src/client/stylesheets/main.scss, src/shared/wallet/contract/choose-function.tsx
/kind api-change
To align action cards center
Fixes #968
=> aligned smart-contract action cards

src/api-gateway/resolvers/antenna-types.ts, src/shared/common/top-bar.tsx
kind ui-change
align the mobile menu dropdown
Fixes #974
=> Align mobile menu

src/client/stylesheets/main.scss, src/shared/common/top-bar.tsx
To fix the alignment of language menu in mobile view
Fixes #978
=> fixed alignment for language menu

src/shared/home/search-box.tsx, src/shared/home/stats/map-card.tsx
To fix all the console errors
Fixes #977
=> fixed console errors

src/shared/common/top-bar.tsx
To align topbar items into mobile view
Fixes #976
=> fixed alignment of topbar items for mobile view

src/api-gateway/resolvers/antenna-types.ts, src/client/stylesheets/main.scss, src/shared/action/action-detail.tsx, src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, src/shared/common/copy-button-clipboard.tsx, src/shared/common/icons/share_icon.svg.tsx, src/shared/wallet/account-section.tsx, src/shared/wallet/broadcast-status.tsx, src/shared/wallet/generate-authorized-message-form-modal.tsx
=> updated action page

src/shared/wallet/decode-contract-data.ts, src/shared/wallet/whitelist-setting.tsx, src/shared/wallet/whitelists.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #991 
```release-note
```
=> rollback to hex data if decode method error

src/shared/address-details/address-details.tsx, src/shared/block/block-detail.tsx, translations/en.yaml
To update the address details page and sync with action details page design
Fixes #1009
=> updated and sync address detail page

src/shared/action/action-detail.tsx, src/shared/actions/actions.tsx
=> Fixed #1011: Using SSR for action details page

src/client/static/manifest.json
=> Fixed #1004: fix console error 

src/shared/common/top-menu-bar.tsx
=> Fixed #1003: cannot scroll after resize to hide the mobile top menu

src/shared/action/action-detail.tsx, src/shared/address-details/address-details.tsx, src/shared/home/home.tsx, src/shared/home/search-box.tsx
To disable focus from search box only on action pages
Fixes #1012
=> added autofocus property and disable focus on action pages

src/shared/wallet/contract/cards.tsx, src/shared/wallet/unlock-by-keystore-file.tsx, src/shared/wallet/unlock-by-mnemonic.tsx, src/shared/wallet/unlock-by-private-key.tsx
/kind bug
To remove the console warning from wallet tabs
Fixes #998
=> Fixed console warning for wallet tabs

src/shared/wallet/contract/cards.tsx, src/shared/wallet/unlock-by-keystore-file.tsx, src/shared/wallet/unlock-by-mnemonic.tsx, src/shared/wallet/unlock-by-private-key.tsx
Reverts iotexproject/iotex-explorer#1030
PR (#1030) cause a side effect that breaks the validation works for the form. 
Fixes: #1025
=> Revert "Fixed console warning for wallet tabs"

src/shared/address-details/address-details.tsx
=> Fixed #1035: explorer crashes with error

src/shared/block/block-detail.tsx
> bug
hovering share should have cursor pointer
Fixes #784 
none
```release-note
```
=> Fixes #784

src/shared/wallet/get-antenna.ts, src/shared/wallet/unlock-by-keystore-file.tsx, src/shared/wallet/unlock-by-mnemonic.tsx, src/shared/wallet/unlock-by-private-key.tsx
=> get antenna add initial option

src/shared/wallet/new-wallet.tsx
To display mnemonic phrase as password type on wallet create
Fixes #1046
=> displayed mnemonic as password type

src/shared/wallet/contract/deploy.tsx
bug
Fixes https://github.com/iotexproject/iotex-antenna/issues/341
none
=> Fixed amount did not work when deploy contract

src/shared/common/top-menu-bar.tsx
To fix the broken link to the playground
Fixes #1061
=> fix broken link

src/client/stylesheets/main.less
=> Fix #1057: Delegate list header overlap

src/shared/pages/action-detail-page.tsx, src/shared/renderer/reciept-address-renderer.tsx
bug
Fixes #1065 
```release-note
```
=> Fixed #1065 No way to get contract address after deployed 

src/shared/home/stats-area.tsx, src/shared/home/stats/productivity-card.tsx, src/shared/home/stats/stats-card.tsx, src/shared/home/stats/votes-card.tsx, translations/en.yaml
ui-change
Fixes #1036
This PR is to show the current epoch number on the home stats area only. For the block list, we would need to update backend API first.
=> Fixed #1036 Show epoch number on iotexscan

src/shared/common/address-name.tsx, src/shared/common/card-details.tsx, src/shared/pages/action-detail-page.tsx, src/shared/pages/address-details-page.tsx, src/shared/pages/block-detail-page.tsx, src/shared/pages/page.tsx
ui-change
Fixes #1069 
This PR will add a copy button beside the share link callout.
=> Fixed #1069 copy should copy only the address

src/electron/package.json
=> upgrade electron version

package.json, src/shared/app.tsx, src/shared/common/action-not-found.tsx, src/shared/common/card-details.tsx, src/shared/common/footer.tsx, src/shared/common/page-nav-bar.tsx, src/shared/common/scroll-top.tsx, src/shared/common/spin-preloader.tsx, src/shared/common/top-menu-bar.tsx, src/shared/home/home.tsx, src/shared/home/stats/map-card.tsx, src/shared/home/stats/stats-card.tsx, src/shared/pages/action-detail-page.tsx, src/shared/pages/address-details-page.tsx, src/shared/pages/block-detail-page.tsx, src/shared/renderer/contract-address-renderer.tsx, src/shared/renderer/input-data-renderer.tsx, src/shared/renderer/text-copy-renderer.tsx, src/shared/renderer/textarea-renderer.tsx, src/shared/renderer/wallet-address-renderer.tsx, src/shared/wallet/broadcast-status.tsx, src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/new-wallet.tsx, src/shared/wallet/unlock-by-keystore-file.tsx, src/shared/wallet/unlock-wallet.tsx, src/shared/wallet/wallet-tabs.tsx, src/shared/wallet/whitelist-setting.tsx, src/shared/wallet/whitelists.tsx, tslint.json
>
> /kind bug
> 
/kind cleanup
> /kind design
> /kind flake
#1078
```release-note
```
=> fix recommended react lint

src/erc20/erc20.ts
bug
Fixes #1076 
```release-note
```
=> Fixed #1076 bid form error handling

src/electron/package.json
bug
Fixes #1077 
The root cause of the issue is that the electron-builder version does not compatible with the new electron version.
=> Fixed #1077 master's broken build 

package.json
/kind bug
TO fix the console warning on wallet form
Fixes #1078
=> Fix console warnings

src/shared/pages/action-list-page.tsx
To display the action type as it is.
Fixes #1082
=> Displayed correct action type

src/shared/home/stats/actions-card.tsx, src/shared/home/stats/candidates-card.tsx, src/shared/home/stats/map-card.tsx, src/shared/home/stats/productivity-card.tsx, src/shared/home/stats/stats-card.tsx, src/shared/home/stats/tps-card.tsx, src/shared/home/stats/votes-card.tsx
bug
This PR is to add a poll interval to stats query for fetching new stats from the server.
This also fixes an issue about stats value animation stuck due to rounding issues.
Fixes #
=> Fixed wrong stats issue

src/shared/pages/action-list-page.tsx
bug
Fixes #1085 
The root cause of the issue is that the GetActions query accepts index start from 0 instead of 1.
none
=> Fixed #1085 Contract page doesn't list anything 

src/client/stylesheets/main.less
To display alert on top 
Fixes #1092
=> displayed alert on top

src/shared/pages/action-list-page.tsx
/kind bug
To display OUT action type in different color not red and fixed numactions console warning.
Fixes #1080
=> updated action type color and fix console warning

src/client/stylesheets/main.less, src/shared/home/block-list.tsx
To add animation to preloader
Fixes #1097
=> added animation to preloader

src/shared/home/stats/productivity-card.tsx
> /kind bug
we were getting when click on home icon on address page.
Fixes #1100
=> fix error when click to home icon

src/client/stylesheets/main.less
alert was hiding behind the page so increased z-index.
Fixes #1099
=> Fixed the alert behind the page

src/shared/pages/action-list-page.tsx
/kind bug
To fix the action table on address page.
Fixes #1101
=> fixed action table pagination issue

config/default.js, src/shared/common/apollo-client.ts
/kind api-change
To point testnet chain to testnet analytics
Fixes #1075
=> points testnet chain to testnet analytics

src/shared/wallet/account-section.tsx
/kind bug
To fix console errors on electron app
Fixes #1103
=> Fix console errors on wallet

package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/api-gateway.ts, src/api-gateway/resolvers/solc.ts, src/server/start-server.ts
feature
This PR is to provide APIs to compile the solidity at server side.
```
compileSolidity(
source:"",
version:""
) {
name
abi
bytecode
}
getSolcVersions{
name
version
}
```
Fixes #
```release-note
```
=> Adding solidity compiler resolver

translations/en.yaml
=> Fixed policy typo issue

src/electron/src/service.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #1121 
```release-note
```
=> force focus window when trigger the contract call

src/electron/src/index.html, src/shared/wallet/contract/cards.tsx, src/shared/wallet/transfer/transfer.tsx
/kind bug
To fix console warning from wallet
Fixes #1103
=> fixed console warning from wallet

package.json, src/shared/home/block-list.tsx, translations/en.yaml
To fix typo and alignment issue
Fixes #1142
=> fixed typo and alignment

src/shared/components/evm-transfer-table.tsx, src/shared/pages/address-details-page.tsx, src/shared/queries.ts, translations/en.yaml
=> Fixed #1141: Support Execution transfers in Explorer

src/client/stylesheets/main.less
To fix the address word break issue
Fixes #1150
=> fixed word break

package.json, src/shared/pages/action-detail-page.tsx, tsconfig.json
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add lodash.omit and fix

src/shared/wallet/broadcast-status.tsx
bug
This PR is to fix an issue reported by community channel as below:
Fixes #
```release-note
```
=> Fixed failed to query action

src/client/stylesheets/main.less, src/shared/common/card-details.tsx, src/shared/common/page-nav-bar.tsx, src/shared/pages/action-detail-page.tsx, src/shared/pages/action-list-page.tsx, src/shared/pages/address-details-page.tsx, src/shared/pages/block-detail-page.tsx, src/shared/pages/block-list-page.tsx, src/shared/pages/page.tsx, src/shared/pages/xrc20-action-list-page.tsx
>
> 
> /kind bug
> /kind design
> /kind flake
Fixes #1184 
```release-note
```
=> fix: ugly layout, margins or paddings

src/shared/common/xrc20-token.tsx, src/shared/pages/action-list-page.tsx, src/shared/renderer/account-balance-renderer.tsx
What type of PR is this?
What this PR does / why we need it:
remove cursor pointer on un-clickable tags
Which issue(s) this PR fixes:
Fixes #1183
=> remove cursor pointer on un-clickable tags

.dockerignore, Dockerfile
>
> /kind bug
> /kind design
> 
/kind feature
> /kind flake
#1190
```release-note
```
=> add docker file

config/enterprise.js, src/api-gateway/api-gateway.graphql, src/shared/common/error-page.tsx, src/shared/common/styles/style-color.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1190
```release-note
```
=> fix enterprise themes

src/client/javascripts/identity-provider-main.tsx, src/server/server-routes.tsx, src/server/set-configs.ts, src/shared/common/top-menu-bar.tsx, src/shared/one-fix-auth-provider/email-password-identity-provider/email-password-identity-provider-handler.tsx, src/shared/one-fix-auth-provider/email-password-identity-provider/identity-provider-main.tsx, src/shared/one-fix-auth-provider/email-password-identity-provider/view/identity-app-container.tsx, src/shared/one-fix-auth-provider/email-password-identity-provider/view/identity-app.tsx
>
> 
/kind bug
> /kind design
> /kind flake
#1210
```release-note
```
=> fix auth client

src/shared/wallet/contract/interact.tsx
=> Fixed #1205: empty interact with contract

src/shared/common/vertical-table.tsx, src/shared/pages/account-list-page.tsx, src/shared/pages/action-list-page.tsx, src/shared/pages/block-list-page.tsx, src/shared/pages/xrc20-action-list-page.tsx
What type of PR is this?
What this PR does / why we need it:
unify all page sizes
Which issue(s) this PR fixes:
Fixes #1188
=> unify all page sizes

README.md
documentation
Fixes #1208 
```release-note
```
=> Fixed 1208: add readme on how to add meta for an address

src/api-gateway/address-meta.json, src/api-gateway/api-gateway.graphql, src/api-gateway/api-gateway.ts, src/api-gateway/resolvers/token.ts, src/server/start-server.ts, src/shared/common/address-name.tsx, src/shared/home/block-list.tsx, src/shared/queries.ts
=> Fixed #1206: [XRC20] remove webBpApolloClient and use address-meta.json file for the mapping

src/shared/pages/xrc20-action-list-page.tsx, src/shared/queries.ts
bug
Fixes #1222 
```release-note
```
=> Fixed #1222: Token transfers page empty

src/shared/wallet/sign-and-send-envelop-modal.tsx
=> feat: add current network in response of contract deploy

config/default.js, src/shared/common/page-nav-bar.tsx, src/shared/common/top-menu-bar.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/queries.ts
=> Fixed #1237: Vita transfer show iotx value and units

src/shared/common/xrc20-token.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/queries.ts, translations/en.yaml
=> [XRC20] Token holders page

src/shared/pages/xrc20-action-list-page.tsx
=> fix nav breadcrumb text inconsistency

src/shared/components/evm-transfer-table.tsx, src/shared/pages/block-list-page.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/pages/xrc20-token-list-page.tsx
Fixes #1253 
Considering the performance especially the mobile, set page size to 15.
=> unify page sizes to 15

translations/zh-CN.yaml
=> update i18n-zh #1251

src/shared/pages/account-list-page.tsx
=> fixed navigation

src/shared/pages/xrc20-action-list-page.tsx, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #1255 #1246 
```release-note
```
=> Fix pagination

src/shared/wallet/wallet.tsx
=> Fix account section styles - segment line overflow

src/shared/wallet/contract/cards.tsx, src/shared/wallet/transfer/transfer.tsx
bug
Fixes #1267  send form's gas cost limit input is not working
```release-note
```
=> Fixes #1267: send form's gas cost limit input is not working

config/default.js, config/production.js, src/server/__tests__/start-server.test.ts, src/server/server-routes.tsx, src/server/start-server.ts, src/shared/common/apollo-ssr.tsx, src/shared/wallet/chain-network-switch.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1271 
```release-note
```
=> Fixed #1271: remove process.env.API_GATEWAY_URL

src/shared/pages/action-detail-page.tsx, translations/en.yaml, translations/zh-CN.yaml
=> add DepositToRewardingFund key to display

package.json, src/shared/common/html-head.tsx, src/shared/common/topbar-ext-menu.tsx, src/shared/home/block-list.tsx
=> Fixed #1221: English string too long in right-side boxes

src/shared/pages/action-detail-page.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes https://github.com/iotexproject/web-bp/issues/1556
```release-note
```
=> Display "Deposit" as a new type of tx

src/shared/pages/action-list-page.tsx
bug
Fixes #1280 
```release-note
```
=> Fixed #1280: Pagination is not mutual exclusive

src/shared/home/stats/actions-card.tsx, src/shared/home/stats/map-card.tsx
optimize
Fixes #1254 
```release-note
```
=> Fixed #1254 optimize analytics loading speed 

src/shared/pages/xrc20-action-list-page.tsx
bug
Fixes #1278 
```release-note
```
=> Fixed #1278: token transfers history is empty 

src/api-gateway/resolvers/meta.ts, src/server/gateways/analytics.ts, src/server/gateways/gateways.ts, src/server/start-server.ts
api-change
Fixes #1180 
```
query {
totalSupply
}
```
```release-note
```
=> Fixed #1180: add graphql API of total supply for the native IOTX token

package.json, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> bump block-producers version

src/shared/app.tsx, src/shared/common/top-bar.tsx, src/shared/common/top-menu-bar.tsx, src/shared/pages/xrc721-action-list-page.tsx, src/shared/pages/xrc721-token-list-page.tsx, src/shared/queries.ts, src/shared/renderer/xrc721-token-address-renderer.tsx, translations/en.yaml
=> Fixed #1229: XRC721 token display on all devices

src/shared/pages/action-detail-page.tsx, src/shared/renderer/index.ts, src/shared/renderer/transfer-payload-renderer.tsx
=> Fixed #1230: [wallet] transfer payload / meta 

src/shared/pages/action-list-page.tsx, src/shared/queries.ts
=> Fixed #1235: Filter action by type

src/shared/renderer/block-height-renderer.tsx
bug
Fixes #1292 
```release-note
```
=> Fixed #1292 fix table styles

src/shared/home/stats-area.tsx, src/shared/home/stats/staked-card.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1274 
=> Fixed #1274: Add a box for "X% IOTX Staked"

src/shared/wallet/contract/interact.tsx
>
/kind bug
> /kind design
> /kind flake
**Which issue(s) this PR fixes**: 1313
Fixes #
```release-note
```
=> format input arguments #1313

src/shared/wallet/account-section.tsx, src/shared/wallet/broadcast-status.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1312
```release-note
```
=> fix electron link network url

src/shared/wallet/unlock-by-ledger.tsx, src/shared/wallet/wallet-actions.ts, src/shared/wallet/wallet-reducer.ts, src/shared/wallet/wallet-tabs.tsx
>
> /kind bug
> /kind design
> /kind flake
**Which issue(s) this PR fixes**: 1310
Fixes #
```release-note
```
=> Hide export tab for ledger

src/shared/wallet/contract/deploy.tsx
>
kind ui-change
> /kind bug
> /kind design
> /kind flake
We need it because now we can deploy contract without version selection.
This PR fixes the issue to deploy contract without selecting the version. 
Fixes #1314 
```release-note
```
=> fixed to deploy contract when version not selected

src/shared/home/stats-area.tsx, src/shared/home/stats/balance-card.tsx, src/shared/home/stats/map-card.tsx, src/shared/home/stats/productivity-card.tsx, translations/en.yaml
>
kind ui-change
> /kind bug
> /kind design
> /kind flake
This PR adds new card Total Circulating Token  on the dashboard and fix the design issues.
Fixes the dashboard issues.
Fixes #1311 
```release-note
```
=> Added card circulating token on dashboard

src/shared/wallet/get-antenna.ts, src/shared/wallet/sign-and-send-envelop-modal.tsx, src/shared/wallet/unlock-by-ledger.tsx
>
> 
/kind bug
> /kind design
> /kind flake
Fixes #1332
```release-note
```
=> ledger SignAndSendEnvelopModal integration

src/api-gateway/resolvers/antenna-types.ts, src/shared/common/get-action-type.ts, src/shared/queries.ts, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1336
```release-note
```
=> add stake type tx

src/shared/common/address-name.tsx, src/shared/pages/action-detail-page.tsx, src/shared/pages/action-list-page.tsx, src/shared/renderer/reciept-address-renderer.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1336
```release-note
```
=> add action type and to in action detail page and action table

src/shared/pages/action-list-page.tsx
Fixes #1300
Fixes "Age" column responsiveness in action list page
=> Fix the responsiveness of table in action-list-page

package.json, src/client/static/bnbridge/hermes.svg, src/shared/home/home.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1338
```release-note
```
=> update bp component

translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Update nsv2 action text

package.json, src/api-gateway/api-gateway.graphql, src/server/server-routes.tsx, src/shared/common/common-metadata.ts, src/shared/common/xrc20-token.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/pages/xrc20-token-list-page.tsx, src/shared/pages/xrc721-action-list-page.tsx, src/shared/pages/xrc721-token-list-page.tsx, src/shared/renderer/token-name-renderer.tsx, translations/en.yaml
Fixes #1346 
```release-note
```
=> add iotex token metadata

translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> rename transaction to action

translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> update action text

src/shared/common/xrc20-token.tsx, src/shared/pages/action-detail-page.tsx, src/shared/renderer/account-balance-renderer.tsx, src/shared/renderer/iotx-value-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1375
```release-note
```
=> format balance and value

src/electron/src/renderer.js, src/shared/common/on-electron-click.ts, src/shared/wallet/contract/choose-function.tsx, src/shared/wallet/contract/contract-layout.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1374 
```release-note
```
=> update title with app version

src/shared/home/stats/map-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> #1377 Display 30-day history of action history

src/shared/pages/action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> #1366 filter action type causing the whole list empty

src/shared/home/stats/map-card.tsx, src/shared/pages/action-detail-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Supporting showing UTF-8 string as a payload #366

src/shared/wallet/transfer/transfer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> #1307 trim address in wallet for sending

translations/de.yaml, translations/en.yaml, translations/it.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> text misalign #1388

src/shared/pages/action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> 1391 wrap age column on action list page

src/shared/pages/action-detail-page.tsx, src/shared/renderer/transfer-payload-renderer.tsx, translations/de.yaml, translations/en.yaml, translations/it.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Show UTF-8 encoding option for payload fields #1334

src/shared/pages/action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> show claim reward amount #1365

src/shared/wallet/transfer/transfer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> send data field is not captured #1396

src/shared/pages/action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1319
```release-note
```
=> fix type column

src/shared/common/top-bar.tsx, translations/de.yaml, translations/en.yaml, translations/it.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add a dropdown to Wallet menu #1401

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Swap i18n and 三 Buttons

.github/workflows/test.yml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> cache github action

config/default.js
>
> /kind bug
> /kind design
> /kind flake
change csp
Fixes #
```release-note
```
=> change csp

src/shared/wallet/unlock-by-mnemonic.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Mnemonic Phrase input should not allow browser to remember phrases #1308

config/default.js, src/shared/common/apollo-ssr.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [improve] set apiGetwayUrl in config instead of dynamic generation #1414

config/default.js, src/shared/common/apollo-ssr.tsx
>
/kind api-change
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> change config var to API_GATEWAY_URL

src/shared/common/icons/iotex.svg.tsx, src/shared/common/vertical-table.tsx, src/shared/common/xrc20-token.tsx, src/shared/home/home.tsx, src/shared/renderer/account-balance-renderer.tsx, src/shared/renderer/iotx-value-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1428 #1429
```release-note
```
=> update logo and fix issue on safari

package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/token.ts, tslint.json
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> update token metadata

src/shared/common/vertical-table.tsx, src/shared/pages/action-detail-page.tsx, src/shared/renderer/action-hash-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> direct expand details of a tx #1425

src/shared/pages/action-detail-page.tsx, src/shared/pages/action-list-page.tsx, src/shared/renderer/action-hash-renderer.tsx, src/shared/renderer/reciept-address-renderer.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1426
```release-note
```
=> add addstake render to and amount

src/shared/home/block-list.tsx, src/shared/home/stats/actions-card.tsx, src/shared/home/stats/candidates-card.tsx, src/shared/home/stats/productivity-card.tsx, src/shared/home/stats/staked-card.tsx, src/shared/home/stats/votes-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Stop requiring data on error #1440

src/shared/common/top-bar.tsx, src/shared/common/topbar-ext-menu.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: switch sites without changing routes #1179

src/shared/common/rules.ts, src/shared/wallet/transfer/transfer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> #1432 [ioPay] Support decimal separator 

src/shared/home/stats-area.tsx, src/shared/home/stats/actions-card.tsx, src/shared/home/stats/candidates-card.tsx, src/shared/home/stats/productivity-card.tsx, src/shared/home/stats/staked-card.tsx, src/shared/home/stats/tps-card.tsx, src/shared/home/stats/votes-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> improve perf of explorer #1422

src/erc20/abi.ts, src/shared/renderer/reciept-address-renderer.tsx, src/shared/wallet/decode-contract-data.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #1451
```release-note
```
=> fix decode hermes methods

src/shared/home/stats/map-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Flip the tx history chart #1456

src/shared/common/vertical-table.tsx, src/shared/wallet/transfer/transfer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> amount on wallet transfer confirmation

src/shared/common/confirm-contract-modal.tsx, src/shared/home/stats/map-card.tsx, src/shared/wallet/account-section.tsx, src/shared/wallet/contract/cards.tsx, src/shared/wallet/contract/deploy.tsx, src/shared/wallet/contract/interact.tsx, src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/whitelist-setting.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix transaction issue due to thousand separator

src/shared/renderer/reciept-address-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> wrap when method line is too long #1463

src/shared/pages/action-detail-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add some space in action detail page #1462

config/default.js, src/server/set-configs.ts, src/server/start-server.ts, src/shared/common/footer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add a version next to copyright #1448

src/shared/common/asset-url.ts, src/shared/home/stats/candidates-card.tsx, src/shared/home/stats/votes-card.tsx, src/shared/wallet/unlock-by-ledger.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> [iopay desktop] smart contract img missing and show blank if enter #1542

src/shared/common/vertical-table.tsx, src/shared/wallet/whitelists.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Capitalize enable and disable #1546

src/shared/wallet/unlock-by-ledger.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Ledger login not working on ioPay 1.0.7 #1589

src/shared/wallet/account-section.tsx, src/shared/wallet/wallet.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> iopay desktop - layout issue #1593

config/default.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> hot fix csp api-gatewaty

src/shared/common/xrc20-token.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/renderer/token-name-renderer.tsx
>
/kind bug
> /kind design
> /kind flake
Adding column for XRC20 on table, for fix issue #1599 
Fixes #1599 
```release-note
```
=> fix: 🐛 adding column on XRC20 table #1599 

src/shared/wallet/transfer/transfer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix disable button

src/shared/pages/xrc20-action-list-page.tsx, src/shared/renderer/token-name-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1644 
```release-note
```
=> Fix issue 1644

.env.tmpl, config/default.js, src/shared/debug-resolver.tsx, src/shared/wallet/add-custom-rpc-form-modal.tsx, src/shared/wallet/chain-network-switch.tsx, src/shared/wallet/get-antenna.ts, src/shared/wallet/wallet-reducer.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Call coreapi directly

package.json, src/electron/package.json, src/electron/src/about.html, src/electron/src/index.html
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix iopay desktop

src/shared/pages/xrc20-action-list-page.tsx, src/shared/queries.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #1633 
```release-note
```
=> fix: fix issue 1633

src/shared/common/xrc20-token.tsx, src/shared/renderer/account-balance-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1662 
```release-note
```
=> fix: use dropdown to select token type and show balance

src/shared/common/xrc20-token.tsx, src/shared/renderer/account-balance-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1665 
```release-note
```
=> fix: fix issue 1665

src/erc20/abi.ts, src/shared/common/flex.tsx, src/shared/renderer/reciept-address-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1658 #1635
```release-note
```
=> add decoded method for mimo exchange and commons

src/client/stylesheets/main.less, src/erc20/token.ts, src/shared/common/styles/style-color.tsx, src/shared/common/xrc20-token.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/renderer/account-balance-renderer.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1664 
```release-note
```
=> Improve token address page

src/erc20/token.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix: refresh token info cache

src/shared/home/stats/productivity-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> query chainMeta from gateway instead of webbp

src/shared/common/confirm-contract-modal.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1673 
```release-note
```
=> fix signAndSend datasource in iopay

src/shared/app.tsx, src/shared/pages/action-list-page.tsx, src/shared/pages/bucket-action-list-page.tsx, src/shared/queries.ts, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1670
```release-note
```
=> add actions by bucket index

config/default.js
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add google analytic to csp connect-src

src/shared/pages/xrc20-token-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> update link to xrc20 address

package.json, src/shared/pages/action-detail-page.tsx, src/shared/renderer/index.ts, src/shared/renderer/xrc20-transfer-renderer.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1669 
```release-note
```
=> add decode log for token transfer

src/erc20/token.ts, src/shared/common/xrc20-token.tsx, src/shared/renderer/xrc20-transfer-renderer.tsx, src/shared/wallet/chain-network-switch.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fixs token decimals render

src/erc20/token.ts, src/shared/common/xrc20-token.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1690
```release-note
```
=> fix amount format with 8 decimal place

src/shared/renderer/account-balance-renderer.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1694
```release-note
```
=> feat: add coin icon in address select list

config/default.js, src/shared/common/TokenTransferRow.tsx, src/shared/renderer/xrc20-transfer-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix hook render

src/shared/common/from-now.ts
>
> /kind bug
> /kind design
> /kind flake
#1703 
Fixes #
```release-note
```
=> fix: fix time ago bug

src/shared/home/stats/staked-card.tsx, src/shared/home/stats/votes-card.tsx, src/shared/queries.ts, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #1713 #1712
```release-note
```
=> fix stake stats

src/shared/home/stats/candidates-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> per currect protocol design, 36 consense delegates.

src/shared/pages/action-list-page.tsx, src/shared/renderer/action-to-renderer.tsx, translations/en.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
**Which issue(s) this PR fixes**: 
Fixes #1731 
```release-note
Update 'to' field ->  Contract Creation & more contract address by query action receipt info.
```
before:
after:
=> update unknown contract field

src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/token.ts, src/shared/common/address-name.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1737 
```release-note
```
=> Fix request query error in console & add addressmeta list api

src/shared/pages/action-detail-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> always show transfers

src/shared/pages/action-detail-page.tsx, src/shared/pages/action-list-page.tsx, src/shared/renderer/index.ts, src/shared/renderer/token-evmTransfer-render.tsx, translations/en.yaml, translations/zh-CN.yaml
=> add new row

src/api-gateway/address-meta.json
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> update burndrop and hermes address map

.github/workflows/release-iopay-desktop.yml
=> Add release to aws S3

src/shared/pages/address-details-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix address

src/shared/home/stats/stats-card.tsx
Reverts iotexproject/iotex-explorer#1763
=> Revert "fix delegate num"

src/shared/home/stats/map-card.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1789 
=> remove the last item on action history chart

src/shared/wallet/contract/cards.tsx
=> increase gas limit to 500000

src/api-gateway/api-gateway.graphql, src/shared/components/stake-action-export.tsx, src/shared/components/stake-action-table.tsx, src/shared/pages/address-details-page.tsx
=> export stake action list

src/shared/wallet/add-custom-tokens-form-modal.tsx
=> List tokens in iopay desktop

src/shared/common/styles/style-media.tsx, src/shared/common/topbar-ext-menu.tsx
=> improve mobile ui

src/shared/wallet/add-custom-tokens-form-modal.tsx
=> Input select custom token

src/shared/wallet/account-section.tsx, translations/en.yaml
=> modify custom token buttom

src/shared/wallet/add-custom-tokens-form-modal.tsx, translations/en.yaml
=> improve custom token dialog

src/shared/wallet/contract/cards.tsx
=> fix cannot send busd-bsc tokens

src/shared/wallet/transfer/transfer.tsx
=> Fix width of token dropdown

src/erc20/erc20.ts, src/erc20/vita.ts, src/shared/wallet/contract/cards.tsx
=> Fix cannot send busd bsc tokens

src/shared/renderer/token-address-renderer.tsx, src/shared/renderer/xrc721-token-address-renderer.tsx
ui-change
add copy button inxrc721_token-address-rederer and token-address-renderer
issue: [#1782 ](https://github.com/iotexproject/iotex-explorer/issues/1782)
=> add copy button inxrc721_token-address-rederer

src/shared/common/from-now.ts
ui-change
fix: Change text to a few seconds ago
issue: [#1760 ](https://github.com/iotexproject/iotex-explorer/issues/1760)
=> Change text to a few seconds ago

src/shared/home/stats/map-card.tsx, src/shared/pages/action-list-page.tsx
=> fix action history

src/electron/src/main.js, src/shared/pages/action-list-page.tsx, src/shared/wallet/add-custom-tokens-form-modal.tsx
=> improve search token by symbol

src/shared/common/card-details.tsx, src/shared/pages/address-details-page.tsx
=> conver address

src/shared/pages/block-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix 修复因查询控件内部无限更新父组件状态导致组件无限重复渲染问题

config/default.js, src/client/javascripts/base-actions.ts, src/client/javascripts/base-reducer.ts, src/client/javascripts/main.tsx, src/electron/global-state.js, src/server/set-configs.ts, src/server/start-server.ts, src/shared/app-container.ts, src/shared/app.tsx, src/shared/common/address-name.tsx, src/shared/common/styles/style-color.tsx, src/shared/common/top-bar.tsx, src/shared/common/vertical-table.tsx, src/shared/renderer/account-address-renderer.tsx, src/shared/renderer/token-address-renderer.tsx, src/shared/renderer/xrc721-token-address-renderer.tsx, src/shared/utils/util.ts
=> convert address

src/shared/common/common-metadata.ts, src/shared/wallet/add-custom-tokens-form-modal.tsx
=> fix token list

src/shared/pages/xrc20-action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix '0x' address in token detail(#1849)

src/shared/pages/xrc20-action-list-page.tsx
Reverts iotexproject/iotex-explorer#1850
=> Revert "fix '0x' address in token detail(#1849)"

src/shared/pages/xrc20-action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1846 
```release-note
```
=> Delete the overview and the profile summary section

src/shared/common/top-bar.tsx, translations/de.yaml, translations/en.yaml, translations/it.yaml, translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Fix  issue 1869

src/shared/common/TokenTransferRow.tsx, src/shared/common/address-name.tsx, src/shared/pages/address-details-page.tsx, src/shared/renderer/contract-address-renderer.tsx, src/shared/renderer/evm-transfer-render.tsx, src/shared/renderer/wallet-address-renderer.tsx, src/shared/utils/util.ts
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Fix address convert

src/shared/wallet/account-section.tsx, src/shared/wallet/transfer/transfer.tsx, translations/en.yaml
=> add max button

src/electron/src/main.js, src/shared/common/rules.ts, src/shared/wallet/transfer/transfer.tsx
=> Add convert button

README.md
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
=> Add "Join Discord" to README.md

src/shared/pages/xrc20-action-list-page.tsx, src/shared/pages/xrc721-action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> convert the address after the address mode switchover

src/shared/app.tsx, src/shared/pages/action-detail-page.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/pages/xrc721-action-list-page.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Support '0x' address in token detail

src/server/server-routes.tsx, src/shared/app.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix route redirect of path 'action/:hash'

src/shared/wallet/transfer/transfer.tsx
=> ui optimation

translations/zh-CN.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> fix Chinese translation of "Total supply"

src/shared/wallet/sign-msg.tsx, src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/unlock-by-mnemonic.tsx, translations/en.yaml
=> some improvements

src/shared/common/copy-button-clipboard.tsx, src/shared/wallet/transfer/transfer.tsx, src/shared/wallet/unlock-by-private-key.tsx
=> add copy button

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> add v2 beta entry

src/shared/common/top-bar.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> feat: attach the path name when click the button "v2 beta"

translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> Rename "Reassign Bucket"

.env.tmpl, config/default.js, package.json, src/api-gateway/api-gateway.graphql, src/api-gateway/resolvers/antenna-types.ts, src/electron/src/main.js, src/server/gateways/gateways.ts, src/server/start-server.ts, src/shared/debug-resolver.tsx, src/shared/wallet/add-custom-rpc-form-modal.tsx, src/shared/wallet/chain-network-switch.tsx, src/shared/wallet/get-antenna.ts, src/shared/wallet/wallet-reducer.ts, src/shared/wallet/wallet-tabs.tsx
=> updat antenna

package.json, src/electron/package.json, src/shared/app.tsx, src/shared/common/TokenTransferRow.tsx, src/shared/common/from-now.ts, src/shared/components/stake-action-export.tsx, src/shared/pages/action-detail-page.tsx, src/shared/pages/block-detail-page.tsx, src/shared/pages/block-list-page.tsx, src/shared/renderer/index.ts, src/shared/wallet/add-custom-tokens-form-modal.tsx, src/shared/wallet/unlock-by-mnemonic.tsx, src/shared/wallet/wallet.tsx
=> update app name

src/electron/package.json
Update @ledgerhq/hw-transport-node-hid
=> fix ledger

src/electron/package.json
=> fix electron updater bug

src/electron/package.json
=> upgrade electron builder for linux
