iotexproject/iotex-desktop-wallet

src/shared/wallet/contract/deploy.js, src/shared/wallet/contract/interact.js, src/shared/wallet/transfer/transfer-input.js, src/shared/wallet/vote/vote-input.js, src/shared/wallet/wallet.js
- to set editable for these inputs, 
update in src/shared/wallet/wallet.js
export const INPUT_READONLY = false;
=> set noneditable gasLimit gasPrice in wallet form

src/client/stylesheets/main.scss, src/shared/action/action-detail.tsx, src/shared/action/action-receipt.tsx, src/shared/common/spin-preloader.tsx
The longest table cell (corresponding to log field of action receipt table) overflows from the screen and it needs a fix.
Fixes #257 
This is my first PR. Feel free to let me know if there's anything done inappropriately.
```release-note
NONE
```
=> Fix #257 Apply full width to spin outside of table so that the table overflows only within itself

src/shared/actions/actions.tsx
bug
Fixes #426 
This page size of Actions table is reduced to 15 rows to optimize loading time. The loading spin would be shown each time pagination load.
```release-note
```
=> Fixed #426: actions loading takes a long time

src/shared/wallet/wallet.tsx
bug
Fixes #463 
The root cause of the issue is `match.url` does not available while using `MemoryRouter`.  
none
=> Fixed #463: [wallet] add contract back to desktop wallet

src/electron/package.json, src/electron/src/main.js, src/electron/src/renderer.js, src/electron/src/solc.js, src/shared/wallet/contract/deploy.tsx
bug
Fixes #496 
The root cause of the issue is the web version of the `solc` was loaded into the renderer web context which was isolated from app context that the whole script is running on. 
To fix this issue, we would need to load native `solc` modules (https://www.npmjs.com/package/solc) at main context and communicate with preloaded renderer context through ipc module (https://electronjs.org/docs/api/ipc-main). 
none
=> Fixed #496: [wallet] cannot find solidity

src/shared/common/apollo-error-handling.ts
bug
Fixes #573 
The root cause of the issue is the general error handling will show notify for all the error happened. There is a common case that the user query for non-existing action, block, etc. for searching the target. Because the non-exist query is usual in-term of searching, the notify is unnecessary and annoying. This PR is to fix it.
=> Fixed #573: [wallet- transfer] query action_exist_by_hash poll shows lots of error

src/erc20/erc20.ts
bug
This PR is to adjust the gas value from estimateGasForAction API to Max(gas, 200000). So the gasLimit should be >= 200000.
Fixes #
```release-note
```
=> Fix low gas issues

src/shared/home/stats/actions-card.tsx, src/shared/home/stats/map-card.tsx, src/shared/queries.ts
bug
Fixes #907 
The root cause of the issue is that apollo client does not support SSR via query method so the initial state of stats is empty. 
=> Fixed #907: strange initial state of stats panel 

src/shared/address-details/address-details.tsx, src/shared/common/navigation.tsx
bug
Fixes #925 
The address list page is not available yet. This fix is meant to remove the breadcrumb from the address detail page.
=> Fixed #925: empty page

src/shared/wallet/unlock-wallet-alert.tsx, src/shared/wallet/wallet.tsx, translations/en.yaml
>
> /kind bug
> /kind design
> /kind flake
show tip modal if wallet is not unlocked when receive message form dapp.
Fixes #941 
```release-note
```
=> remind unlock wallet

webpack.js
To fix the warnings we getting on **npm run watch** then I researched and found that we can exclude these to suppress warnings.
Fixes #1049
=> Suppressed warning for source-map-loader

src/shared/pages/address-details-page.tsx
/kind bug
To display the error page when data is empty.
Fixes #1102
=> displayed error when data is empty

src/shared/common/apollo-client.ts, src/shared/pages/action-list-page.tsx
bug
This PR is to limit the request rate to GraphQL endpoint to 5 requests per second. 
Fixes #1158 
The root cause of the issue is that too many requests to the GraphQL endpoint caused by the action fee renderer at the same time. 
NONE
=> Fixed #1158: Action fee renderer error

src/shared/renderer/token-transfer-renderer.tsx
bug
This PR is to fix alert not exist error right after sending VITA.
Fixes #
none
=> Fixed not exist error alert right after sending VITA

src/shared/pages/address-details-page.tsx
feature
Fixes #1191
1. Go to address page
2. The url will change if you click different tabs that picture highlight.
```release-note
```
=> add different hashroute for tabs

src/shared/pages/xrc20-action-list-page.tsx, src/shared/pages/xrc721-action-list-page.tsx
bug
This PR is to fix the error while querying token holders for an empty token address. The fix is to disable the token holder's tab if there is no token address defined (tokentxns page ).
Fixes #1291 
```release-note
```
=> Fixed #1291 errors failed to query analytics xrc20

src/shared/pages/action-detail-page.tsx
bug
This PR is to return 404 status code for an invalid action hash in terms of hash length (64). If the hash length valid we still need to return status 200 for checking pending hash.
Fixes #878 
```release-note
```
=> Fix #878 Return 404 for invalid action hash

src/shared/pages/action-list-page.tsx
Fixes #1298 
This commit will fix the incorrect display on the action-list-page.
=> Fix incorrect display of Age (50 years) in action-list-page

src/shared/renderer/action-hash-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
=> change failed action icon to use the yellow one #1409

src/client/stylesheets/main.less, src/shared/wallet/account-section.tsx, src/shared/wallet/transfer/transfer.tsx, translations/de.yaml, translations/en.yaml, translations/it.yaml, translations/zh-CN.yaml
>
/kind bug
> /kind design
> /kind flake
Fixes #1579 , And find a exist button tag nested error.
Fixes #1579
Find a exist bug:
the reason is button tag nested:
resolve:
```release-note
1. Nested `<button>` case, rename child node to <a> and fixed css style.
2. fix #1579
```
=> Hotfix/resolve issue #1579

src/shared/common/xrc20-token.tsx, src/shared/pages/xrc20-action-list-page.tsx, src/shared/renderer/token-name-renderer.tsx
>
> /kind bug
> /kind design
> /kind flake
Fixes #1699
```release-note
```
=> fix: 1. improve display xrc20 symbol and name 2. fix document title
